#!/bin/bash

CHECK=$1
if [ -z "$2" ]
then
	HOST=127.0.0.1
else
	HOST="$2"
fi

[ -n "$CHECK" ] \
	|| exit 2
[ -n "$HOST" ] \
	|| exit 2

if [ "$CHECK" = "-a" ]
then
	CHECKS="$(nrpe-list -s)"
else
	CHECKS="$CHECK"
fi

for check in $CHECKS
do
	/usr/lib64/nagios/plugins/check_nrpe -H "$HOST" -c "$check"
done
